name: ci_python

on:
  push:
    paths:
      - "do.py"
      - ".github/workflows/python.yml"
      - "code-experiments/build/python/*"
      - "code-experiments/src/**.c"
      - "code-experiments/src/**.h"
  pull_request:
    branches: [ master, development ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.version}}
        cache: "pip"
    - run: pip install -r code-experiments/build/python/requirements.txt
    - run: python do.py verbose run-python --user and-test
