version: 2

on:
  push:
    branches-ignore:
      - 'gh-pages'
    paths-ignore:
      - 'README.md'

jobs:

  test_ubuntu_rolling_python3:
    docker:
      - image: ubuntu:rolling
        environment:
          CC: gcc
    working_directory: ~/coco
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: apt-get update -qy
      - run:
          name: Set time zone
          command: ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime
      - run:
          name: Install python-dev with apt-get
          command: DEBIAN_FRONTEND=noninteractive apt-get install -y python3-dev
      - run:
          name: Install pip with apt-get
          command: apt-get install -y python3-pip
      - run:
          name: Install build-essential with apt-get
          command: apt-get install -y build-essential
      - run:
          name: Install git with apt-get
          command: apt-get install -y git
      - run:
          name: Install cargo with apt-get
          command: apt-get install -y rust-all
      - run:
          name: Install libclang for bindgen with apt-get
          command: apt-get install -y libclang-dev
      - run:
          name: Install bindgen with cargo
          command: cargo install bindgen-cli
#      - run:
#          name: Install tkinter with apt-get
#          command: apt-get install -y python3-tk
      - run:
          name: Install python packages with pip
          command: pip3 install --upgrade matplotlib numpy setuptools \
                                          six scipy pytest cython
      - run:
          name: Create symbolic link to python binaries
          command: ln -s /usr/bin/python3 /usr/bin/python
      - run:
          name: Install coco python
          command: python3 do.py run-python install-user
      - run:
          name: Install coco post-processing
          command: python3 do.py install-postprocessing install-user
      - run:
          name: Run the example experiment
          command: |
            cd ~/coco/code-experiments/build/python
            python3 example_experiment.py bbob
      - run:
          name: Post-process the results
          command: |
            cd ~/coco/code-experiments/build/python
            python3 -m cocopp -o ./postproc ./exdata
      - run:
          name: Run coco Python 3 tests
          command: python3 do.py test-python
          no_output_timeout: 1800
      - run:
          name: Install mlocate
          command: |
            apt-get install -y mlocate
            updatedb
      - run:
          name: Install octave for octave tests
          command: |
            DEBIAN_FRONTEND=noninteractive apt-get install -y liboctave-dev
            updatedb
      - run:
          name: Run coco octave tests
          command: python3 do.py test-octave
          no_output_timeout: 1800
      - run:
          name: Install jdk for java tests
          command: |
            apt-get install -y openjdk-11-jdk
            updatedb
      - run:
          name: Run coco octave tests
          command: python3 do.py test-java
          no_output_timeout: 1800
      - run:
          name: Run coco pre-processing tests
          command: python3 do.py test-preprocessing install-user
          no_output_timeout: 1800
      - run:
          name: Run coco post-processing tests
          command: python3 do.py test-postprocessing install-user
          no_output_timeout: 5400
      - run:
          name: Run coco C
          command: python do.py run-c
      - run:
          name: Run coco C tests
          command: python do.py test-c
          no_output_timeout: 1800
      - run:
          name: Run coco Rust
          command: |
            export PATH=~/.cargo/bin:$PATH
            python do.py run-rust
      - run:
          name: Run coco Rust tests
          command: |
            export PATH=~/.cargo/bin:$PATH
            python do.py test-rust
          no_output_timeout: 1800
      - run:
          name: Run regression test
          command: python do.py test-suites
          no_output_timeout: 1800



workflows:

  version: 2
  test-matrix:
    jobs:
      - test_ubuntu_rolling_python3

